# Generated by Django 4.1.5 on 2023-01-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_cart_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size',
            new_name='description',
        ),
    ]
