# Generated by Django 4.1.5 on 2023-01-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_size_cart_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='description',
            new_name='size',
        ),
    ]
